name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "True"
          SHOW_EDITORS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SYMBOL_VERSION: 2
          SHOW_UPDATED_DATE: "True"
