name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "1 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "True"
          SHOW_LANGUAGE: "False"
          SHOW_EDITORS: "False"
